/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatecEventos.views;

import br.com.fatecEventos.dao.EventoDAO;
import br.com.fatecEventos.logic.LimparCampos;
import br.com.fatecEventos.model.Evento;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class CriarEvento extends javax.swing.JDialog {

    private static String novaData = "";
    private static EventoDAO eventoDAO;
    private static Connection con;
    private static int tecla = 0;

    /**
     * Creates new form CriarEvento
     */
    public CriarEvento() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        String path = new File(".").getCanonicalPath();
        String nf = path.replace("dist", "");
        String arqCam = nf + "\\src\\br\\com\\fatecEventos\\images\\icone_JFrame.png";
        ImageIcon icone = new ImageIcon(arqCam);
        setIconImage(icone.getImage());
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeEvento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ftfDataEvento = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarEvento = new javax.swing.JButton();
        btnCancelarEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("fatecEventos 1.0");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome do Evento:");

        txtNomeEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeEventoKeyPressed(evt);
            }
        });

        jLabel3.setText("Data do Evento:");

        ftfDataEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfDataEventoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeEvento)
                    .addComponent(ftfDataEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIAR EVENTO");
        jLabel1.setOpaque(true);

        btnCadastrarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Botao_Concluir.png"))); // NOI18N
        btnCadastrarEvento.setText("Cadastrar");
        btnCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEventoActionPerformed(evt);
            }
        });
        btnCadastrarEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarEventoKeyPressed(evt);
            }
        });

        btnCancelarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Botao_Cancelar.png"))); // NOI18N
        btnCancelarEvento.setText("Cancelar");
        btnCancelarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEventoActionPerformed(evt);
            }
        });
        btnCancelarEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarEventoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 311, Short.MAX_VALUE)
                        .addComponent(btnCancelarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarEvento)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEvento)
                    .addComponent(btnCancelarEvento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEventoActionPerformed
        LimparCampos.limpaCampos(jPanel1);
        dispose();
    }//GEN-LAST:event_btnCancelarEventoActionPerformed

    private void btnCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEventoActionPerformed
        try {
            cadastraEvento();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnCadastrarEventoActionPerformed

    private void ftfDataEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfDataEventoKeyPressed
        tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            try {
                cadastraEvento();
            } catch (Exception e) {

            }
        } else if (tecla != KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_ENTER) {
            int numeroData = ftfDataEvento.getText().length();
            novaData = ftfDataEvento.getText();
            if (numeroData == 2 || numeroData == 5) {
                novaData += "/";
                ftfDataEvento.setText(novaData);
            }
        }
    }//GEN-LAST:event_ftfDataEventoKeyPressed

    private void txtNomeEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEventoKeyPressed
        tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            try {
                cadastraEvento();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_txtNomeEventoKeyPressed

    private void btnCadastrarEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarEventoKeyPressed
        tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            try {
                cadastraEvento();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btnCadastrarEventoKeyPressed

    private void btnCancelarEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarEventoKeyPressed
        tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarEventoKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            try {
                this.dispose();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CriarEvento().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CriarEvento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEvento;
    private javax.swing.JButton btnCancelarEvento;
    private static javax.swing.JFormattedTextField ftfDataEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField txtNomeEvento;
    // End of variables declaration//GEN-END:variables

    public static void cadastraEvento() throws SQLException {
        String nomeEvento = txtNomeEvento.getText();
        String dataEvento = ftfDataEvento.getText();
        if (!nomeEvento.equals("") && !dataEvento.equals("")) {
            eventoDAO = new EventoDAO();
            eventoDAO.CadastrarEvento(con, new Evento(0, nomeEvento, dataEvento));
            LimparCampos.limpaCampos(jPanel1);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }
}
