/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatecEventos.views;

import br.com.fatecEventos.dao.CicloDAO;
import br.com.fatecEventos.dao.EventoDAO;
import br.com.fatecEventos.dao.ItemDAO;
import br.com.fatecEventos.dao.PessoaDAO;
import br.com.fatecEventos.dao.TurnoDAO;
import br.com.fatecEventos.logic.LimparCampos;
import br.com.fatecEventos.model.Ciclo;
import br.com.fatecEventos.model.Evento;
import br.com.fatecEventos.model.Item;
import br.com.fatecEventos.model.Pessoa;
import br.com.fatecEventos.model.Turno;
import static br.com.fatecEventos.views.CriarEvento.cadastraEvento;
import com.mysql.jdbc.Connection;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JToolTip;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author lucas
 */
public class CriarPessoa extends javax.swing.JDialog {

    private static EventoDAO eventoDAO;
    private static CicloDAO cicloDAO;
    private static TurnoDAO turnoDAO;
    private static Connection con;
    private static PessoaDAO pessoaDAO;
    private static ItemDAO itemDAO;
    private static ArrayList<Evento> arrayEventos = new ArrayList<>();
    private static ArrayList<Ciclo> arrayCiclo = new ArrayList<>();
    private static ArrayList<Turno> arrayTurno = new ArrayList<>();
    private static ArrayList<Pessoa> arrayPessoa = new ArrayList<>();
    private static ArrayList<Item> arrayItem = new ArrayList<>();
    private int tecla = 0, confirmacaoEmail = 0;
    private Point p1 = null, p2 = null, p3 = null, p4 = null;
    private PopupFactory popupFactory = PopupFactory.getSharedInstance();
    private JComponent component1 = null, component2 = null, component3 = null, component4 = null;
    private JToolTip tip1 = null, tip2 = null, tip3 = null, tip4 = null;
    private Popup popupNome = null, popupEmail = null, popupData = null, popupCurso = null;

    /**
     * Creates new form CriarPessoa
     */
    public CriarPessoa() throws SQLException, IOException {
        initComponents();
        setLocationRelativeTo(null);
        String path = new File(".").getCanonicalPath();
        String nf = path.replace("dist", "");
        String arqCam = nf + "\\src\\br\\com\\fatecEventos\\images\\icone_JFrame.png";
        ImageIcon icone = new ImageIcon(arqCam);
        setIconImage(icone.getImage());
        eventoDAO = new EventoDAO();
        arrayEventos = eventoDAO.PesquisarComboBox(con, "SELECT * FROM tb_evento");
        comboBoxNomeEvento();
        turnoDAO = new TurnoDAO();
        arrayTurno = turnoDAO.PesquisarComboBox(con, "SELECT nm_turno FROM tb_turno");
        comboBoxTurno();
        cicloDAO = new CicloDAO();
        arrayCiclo = cicloDAO.PesquisarComboBox(con, "SELECT num_ciclo FROM tb_ciclo");
        comboBoxCiclo();
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ftfData = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbCiclo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ftfContribuicao = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbEventos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("fatecEventos 1.0");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR PESSOA");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        tfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeFocusLost(evt);
            }
        });

        jLabel3.setText("Data:");

        ftfData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfDataFocusLost(evt);
            }
        });
        ftfData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfDataKeyPressed(evt);
            }
        });

        jLabel5.setText("Curso:");

        tfCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCursoFocusLost(evt);
            }
        });

        jLabel6.setText("Turno:");

        cbTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manhã", "Tarde", "Noite" }));

        jLabel7.setText("Ciclo:");

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel4.setText("Contibuição:");

        ftfContribuicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfContribuicaoFocusLost(evt);
            }
        });
        ftfContribuicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfContribuicaoKeyPressed(evt);
            }
        });

        jLabel9.setText("Email:");

        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ftfContribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfCurso))
                            .addComponent(tfEmail))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfContribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfEmail, tfNome});

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Botao_Concluir.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Botao_Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Nome do Evento:");

        cbEventos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        LimparCampos.limpaCampos(jPanel1);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ftfDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfDataKeyPressed
        tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            try {
                cadastraEvento();
            } catch (Exception e) {

            }
        } else if (tecla != KeyEvent.VK_BACK_SPACE && tecla != KeyEvent.VK_ENTER) {
            int numeroData = ftfData.getText().length();
            String novaData = ftfData.getText();
            if (numeroData == 2 || numeroData == 5) {
                novaData += "/";
                ftfData.setText(novaData);
            }
        }
    }//GEN-LAST:event_ftfDataKeyPressed

    private void ftfContribuicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfContribuicaoKeyPressed
    }//GEN-LAST:event_ftfContribuicaoKeyPressed

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        popupEmail.hide();
    }//GEN-LAST:event_tfEmailFocusLost

    private void ftfContribuicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfContribuicaoFocusLost
        if (ftfContribuicao.getText().toString().equals("")) {
            ftfContribuicao.setText("0,00");
        } else {

            int caracteres = ftfContribuicao.getText().length();
            String aux = "";
            String novoValor = "";
            int cont = 0;
            int quantCaracteresContribuicao = 0;
            while (cont < caracteres) {
                aux = ftfContribuicao.getText().substring(cont, cont + 1);
                if (aux.equals(",")) {
                    quantCaracteresContribuicao = ftfContribuicao.getText().replace(",", "").length();
                    aux = "";
                } else if (aux.equals(".")) {
                    quantCaracteresContribuicao = ftfContribuicao.getText().replace(".", "").length();
                    aux = "";
                } else if (!(aux.equals(",") && aux.equals("."))) {
                    quantCaracteresContribuicao = ftfContribuicao.getText().length();
                    aux = aux;
                }
                novoValor += aux;
                cont++;
            }
            String formatacao = "";
            if (quantCaracteresContribuicao == 1) {
                formatacao = "0,0#";
            } else if (quantCaracteresContribuicao == 2) {
                formatacao = "0,##";
            } else if (quantCaracteresContribuicao == 3) {
                formatacao = "#,##";
            } else if (quantCaracteresContribuicao == 4) {
                formatacao = "##,##";
            } else if (quantCaracteresContribuicao == 5) {
                formatacao = "###,##";
            } else if (quantCaracteresContribuicao == 6) {
                formatacao = "#.###,##";
            } else if (quantCaracteresContribuicao == 7) {
                formatacao = "##.###,##";
            } else if (quantCaracteresContribuicao == 8) {
                formatacao = "###.###,##";
            } else if (quantCaracteresContribuicao == 9) {
                formatacao = "#.###.###,##";
            } else if (quantCaracteresContribuicao == 10) {
                formatacao = "##.###.###,##";
            } else if (quantCaracteresContribuicao == 11) {
                formatacao = "###.###.###,##";
            }
            ftfContribuicao.setText(format(formatacao, novoValor));
        }
    }//GEN-LAST:event_ftfContribuicaoFocusLost

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nmEvento = cbEventos.getSelectedItem().toString();
        if (tfNome.getText().equals("")) {
            tfNome.grabFocus();
            tfNome.setToolTipText("Preencha com seu nome");
            p1 = tfNome.getLocationOnScreen();
            tip1 = tfNome.createToolTip();
            tip1.setTipText(tfNome.getToolTipText());
            component1 = tfNome;
            popupNome = popupFactory.getPopup(component1, tip1, p1.x, p1.y - 18);
            popupNome.show();
        } else if (tfEmail.getText().equals("")) {
            tfEmail.grabFocus();
            tfEmail.setToolTipText("Preencha com seu email");
            p2 = tfEmail.getLocationOnScreen();
            tip2 = tfEmail.createToolTip();
            tip2.setTipText(tfEmail.getToolTipText());
            component2 = tfEmail;
            popupEmail = popupFactory.getPopup(component2, tip2, p2.x, p2.y - 18);
            popupEmail.show();
        } else if (ftfData.getText().equals("")) {
            ftfData.grabFocus();
            ftfData.setToolTipText("Preencha com a data do seu nascimento");
            p3 = ftfData.getLocationOnScreen();
            tip3 = ftfData.createToolTip();
            tip3.setTipText(ftfData.getToolTipText());
            component3 = ftfData;
            popupData = popupFactory.getPopup(component3, tip3, p3.x, p3.y - 18);
            popupData.show();
        } else if (tfCurso.getText().equals("")) {
            tfCurso.grabFocus();
            tfCurso.setToolTipText("Preencha com o seu curso");
            p4 = tfCurso.getLocationOnScreen();
            tip4 = tfCurso.createToolTip();
            tip4.setTipText(tfCurso.getToolTipText());
            component4 = tfCurso;
            popupCurso = popupFactory.getPopup(component3, tip4, p4.x, p4.y - 18);
            popupCurso.show();
        } else if (ftfContribuicao.getText().equals("")) {
            ftfContribuicao.setText("0.00");
        } else if (!(tfNome.getText().equals("") || tfEmail.getText().equals("") || ftfData.getText().equals("") || tfCurso.getText().equals(""))) {
            try {
                // FAZ CADASTRO
                cadastraPessoa(nmEvento);
            } catch (SQLException ex) {
                Logger.getLogger(CriarPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            LimparCampos.limpaCampos(jPanel1);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    public static void cadastraPessoa(String nmE) throws SQLException {
        eventoDAO = new EventoDAO();
        arrayEventos = eventoDAO.PesquisarComboBox(con, "SELECT * FROM tb_evento WHERE nm_evento = '" + nmE + "'");
        pessoaDAO = new PessoaDAO();
        pessoaDAO.CadastrarPessoa(con, new Pessoa(0, tfNome.getText(), tfEmail.getText(), ftfData.getText(), tfCurso.getText(), ftfContribuicao.getText(), cbTurno.getSelectedItem().toString(), Integer.parseInt(cbCiclo.getSelectedItem().toString()), ""));
        int idPessoa = pessoaDAO.PesquisarUltimaPessoa(con);
        int idEvento = 0;
        int cont = 0;
        while (arrayEventos.size() > cont) {
            idEvento = arrayEventos.get(cont).getCodigo();
            cont++;
        }
        itemDAO = new ItemDAO();
        itemDAO.CadastrarItem(con, new Item(0, idPessoa, idEvento));
    }

    private void tfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusLost
        popupNome.hide();
    }//GEN-LAST:event_tfNomeFocusLost

    private void ftfDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfDataFocusLost
        popupData.hide();
    }//GEN-LAST:event_ftfDataFocusLost

    private void tfCursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCursoFocusLost
        popupCurso.hide();
    }//GEN-LAST:event_tfCursoFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int t = evt.getKeyCode();
        if (t == KeyEvent.VK_ESCAPE) {
            try {
                this.dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private static String format(String pattern, Object value) {
        MaskFormatter mask;
        try {
            mask = new MaskFormatter(pattern);
            mask.setValueContainsLiteralCharacters(false);
            return mask.valueToString(value);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CriarPessoa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CriarPessoa.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(CriarPessoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private static javax.swing.JComboBox cbCiclo;
    private static javax.swing.JComboBox cbEventos;
    private static javax.swing.JComboBox cbTurno;
    private static javax.swing.JFormattedTextField ftfContribuicao;
    private static javax.swing.JFormattedTextField ftfData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JTextField tfCurso;
    private static javax.swing.JTextField tfEmail;
    private static javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

//    public void imgLabel(int nmLabel) throws IOException {
//        // diretório que será listado.  
//        System.out.println("cheguei");
//        caminho = "C:\\Users\\lucas\\Documents\\NetBeansProjects\\fatecEventos\\src\\br\\com\\fatecEventos\\imgUsuarios";
//        File baseFolder = new File(caminho);
//        arquivo = (caminho + "\\" + nmLabel + ".jpg");
//        // obtem a lista de arquivos  
//        BufferedImage img = ImageIO.read(new File(arquivo));
//        ImageIcon icon = new ImageIcon(img);
//        icon.setImage(icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), 100));
//        lblFoto.setIcon(icon);
//
//    }
    public static void comboBoxNomeEvento() {
        cbEventos.removeAllItems();
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        String novaData = formatador.format(data);
        int diaAtual = Integer.parseInt(novaData.substring(0, 2));
        int mesAtual = Integer.parseInt(novaData.substring(3, 5));
        int anoAtual = Integer.parseInt(novaData.substring(6, 10));

        int cont = 0;
        while (arrayEventos.size() > cont) {
            int diaBanco = Integer.parseInt(arrayEventos.get(cont).getDataEvento().substring(0, 2));
            int mesBanco = Integer.parseInt(arrayEventos.get(cont).getDataEvento().substring(3, 5));
            int anoBanco = Integer.parseInt(arrayEventos.get(cont).getDataEvento().substring(6, 10));
            if (anoAtual == anoBanco) {
                if (mesAtual < mesBanco) {
                    cbEventos.addItem(arrayEventos.get(cont).getNomeEvento());
                } else if (mesAtual == mesBanco) {
                    if (diaAtual <= diaBanco) {
                        cbEventos.addItem(arrayEventos.get(cont).getNomeEvento());
                    } else {
                    }
                } else if (mesAtual > mesBanco) {

                }
            } else if (anoAtual < anoBanco) {
                cbEventos.addItem(arrayEventos.get(cont).getNomeEvento());
            }
            cont++;
        }
    }

    public static void comboBoxTurno() {
        cbTurno.removeAllItems();

        int cont = 0;
        while (arrayTurno.size() > cont) {
            cbTurno.addItem(arrayTurno.get(cont).getNm_turno());
            cont++;
        }
    }

    public static void comboBoxCiclo() {
        cbCiclo.removeAllItems();

        int cont = 0;
        while (arrayCiclo.size() > cont) {
            cbCiclo.addItem(arrayCiclo.get(cont).getNum_ciclo());
            cont++;
        }
    }

}
