/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatecEventos.views;

import br.com.fatecEventos.dao.EventoDAO;
import br.com.fatecEventos.dao.UsuarioDAO;
import br.com.fatecEventos.logic.AtualizadorHorario;
import br.com.fatecEventos.logic.TirarFoto;
import static br.com.fatecEventos.logic.TirarFoto.arquivo;
import br.com.fatecEventos.model.Evento;
import br.com.fatecEventos.model.Usuario;
import com.mysql.jdbc.Connection;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lucas
 */
public class Principal extends javax.swing.JFrame {

    private static EventoDAO eventoDAO;
    private static Connection con;
    private static ArrayList<Evento> arrayEventos = new ArrayList<>();
    private String nomeEvento = "";
    private static int codigoImagem = 0;
    private static ArrayList<Usuario> arrayUsuario = new ArrayList<>();
    private static UsuarioDAO usuarioDAO = new UsuarioDAO();
    private static String caminhoGlobal = "";
    private static Random r = new Random();
    private static int nm = r.nextInt() * 5;
    private static TirarFoto tirarFoto;

    /**
     * Creates new form Principal
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public Principal() throws SQLException, IOException {
        initComponents();
        setLocationRelativeTo(null);
        String path = new File(".").getCanonicalPath();
        String nf = path.replace("dist", "");
        String arqCam = nf + "\\src\\br\\com\\fatecEventos\\images\\icone_JFrame.png";
        ImageIcon icone = new ImageIcon(arqCam);
        setIconImage(icone.getImage());
        AtualizadorHorario ah = new AtualizadorHorario(lblData);
        ah.mostrarData(true);
        Thread thData = ah;
        thData.start();
        System.out.println("Principal");
        verificaEvento();
        //verificaImagem();
        Thread t = new Thread(new CarregaImagem());
        t.start();
    }

    public static void nomeUsuario(int id, String nome, String senha, String email, String caminho) {
        lblNomeUsuario.setText(nome);
        codigoImagem = id;
        caminhoGlobal = caminho;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        imgUsuario = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCriar = new javax.swing.JMenu();
        miEventoCriar = new javax.swing.JMenuItem();
        miPessoaCriar = new javax.swing.JMenuItem();
        mPesquisar = new javax.swing.JMenu();
        miEventoPesquisar = new javax.swing.JMenuItem();
        miPessoaPesquisar = new javax.swing.JMenuItem();
        mAnotacoes = new javax.swing.JMenu();
        mWord = new javax.swing.JMenu();
        miNovoDocumentoWord = new javax.swing.JMenuItem();
        miAbrirDocumentoWord = new javax.swing.JMenuItem();
        mExcel = new javax.swing.JMenu();
        miNovoDocumentoExcel = new javax.swing.JMenuItem();
        miAbriDocumentoExcel = new javax.swing.JMenuItem();
        mEmail = new javax.swing.JMenu();
        miEnviarEmail = new javax.swing.JMenuItem();
        mSobre = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fatecEventos 1.0");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCalendar1.setBackground(new java.awt.Color(255, 255, 255));
        jCalendar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jCalendar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(102, 153, 255));
        jCalendar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCalendar1.setOpaque(false);
        jCalendar1.setSundayForeground(new java.awt.Color(255, 102, 0));
        jCalendar1.setWeekOfYearVisible(false);
        jCalendar1.setWeekdayForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        imgUsuario.setBackground(new java.awt.Color(204, 204, 204));
        imgUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Label_Usuario.png"))); // NOI18N
        imgUsuario.setOpaque(true);
        imgUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUsuarioMouseClicked(evt);
            }
        });

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNomeUsuario.setText("jLabel2");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblData.setText("jLabel3");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Label_Horas.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));

        mCriar.setForeground(new java.awt.Color(255, 255, 255));
        mCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Novo.png"))); // NOI18N
        mCriar.setText("Criar");
        mCriar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miEventoCriar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miEventoCriar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miEventoCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Evento.png"))); // NOI18N
        miEventoCriar.setText("Evento");
        miEventoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEventoCriarActionPerformed(evt);
            }
        });
        mCriar.add(miEventoCriar);

        miPessoaCriar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miPessoaCriar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miPessoaCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Pessoas.png"))); // NOI18N
        miPessoaCriar.setText("Pessoa");
        miPessoaCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoaCriarActionPerformed(evt);
            }
        });
        mCriar.add(miPessoaCriar);

        jMenuBar1.add(mCriar);

        mPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        mPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Pesquisar.png"))); // NOI18N
        mPesquisar.setText("Pesquisar");
        mPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miEventoPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miEventoPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miEventoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Evento.png"))); // NOI18N
        miEventoPesquisar.setText("Evento");
        miEventoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEventoPesquisarActionPerformed(evt);
            }
        });
        mPesquisar.add(miEventoPesquisar);

        miPessoaPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miPessoaPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miPessoaPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Pessoas.png"))); // NOI18N
        miPessoaPesquisar.setText("Pessoa");
        miPessoaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoaPesquisarActionPerformed(evt);
            }
        });
        mPesquisar.add(miPessoaPesquisar);

        jMenuBar1.add(mPesquisar);

        mAnotacoes.setForeground(new java.awt.Color(255, 255, 255));
        mAnotacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Anotacoes.png"))); // NOI18N
        mAnotacoes.setText("Anotações");
        mAnotacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Word.png"))); // NOI18N
        mWord.setText("Word");
        mWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miNovoDocumentoWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miNovoDocumentoWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItemNovo.png"))); // NOI18N
        miNovoDocumentoWord.setText("Novo Documento");
        miNovoDocumentoWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoDocumentoWordActionPerformed(evt);
            }
        });
        mWord.add(miNovoDocumentoWord);

        miAbrirDocumentoWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miAbrirDocumentoWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_AbrirDocumento.png"))); // NOI18N
        miAbrirDocumentoWord.setText("Abrir Documento");
        miAbrirDocumentoWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirDocumentoWordActionPerformed(evt);
            }
        });
        mWord.add(miAbrirDocumentoWord);

        mAnotacoes.add(mWord);

        mExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Excel.png"))); // NOI18N
        mExcel.setText("Excel");
        mExcel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miNovoDocumentoExcel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miNovoDocumentoExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItemNovo.png"))); // NOI18N
        miNovoDocumentoExcel.setText("Novo Documento");
        miNovoDocumentoExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoDocumentoExcelActionPerformed(evt);
            }
        });
        mExcel.add(miNovoDocumentoExcel);

        miAbriDocumentoExcel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miAbriDocumentoExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_AbrirDocumento.png"))); // NOI18N
        miAbriDocumentoExcel.setText("Abrir Documento");
        miAbriDocumentoExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbriDocumentoExcelActionPerformed(evt);
            }
        });
        mExcel.add(miAbriDocumentoExcel);

        mAnotacoes.add(mExcel);

        jMenuBar1.add(mAnotacoes);

        mEmail.setForeground(new java.awt.Color(255, 255, 255));
        mEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Email.png"))); // NOI18N
        mEmail.setText("Email");
        mEmail.setEnabled(false);
        mEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miEnviarEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miEnviarEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Enviar.png"))); // NOI18N
        miEnviarEmail.setText("Enviar Email");
        miEnviarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEnviarEmailActionPerformed(evt);
            }
        });
        mEmail.add(miEnviarEmail);

        jMenuBar1.add(mEmail);

        mSobre.setForeground(new java.awt.Color(255, 255, 255));
        mSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Sobre.png"))); // NOI18N
        mSobre.setText("Sobre");
        mSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Interrogacao.png"))); // NOI18N
        miSobre.setText("Sobre o Sistema");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mSobre.add(miSobre);

        jMenuBar1.add(mSobre);

        mSair.setForeground(new java.awt.Color(255, 255, 255));
        mSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/Menu_Sair.png"))); // NOI18N
        mSair.setText("Sair");
        mSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/MenuItem_Sair.png"))); // NOI18N
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mSair.add(miSair);

        jMenuBar1.add(mSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblNomeUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void chamaMensagemEvento() throws IOException {
        AvisoEvento avisoEvento = new AvisoEvento();
        avisoEvento.recebeNomeEvento(nomeEvento);
        avisoEvento.setVisible(true);
    }

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        Sair sair = null;
        try {
            sair = new Sair();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        sair.setVisible(true);
    }//GEN-LAST:event_miSairActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        Sobre sobre = null;
        try {
            sobre = new Sobre();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        sobre.setVisible(true);
    }//GEN-LAST:event_miSobreActionPerformed

    private void miEventoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEventoPesquisarActionPerformed
        PesquisarEvento pesquisarEvento = null;
        try {
            pesquisarEvento = new PesquisarEvento();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        pesquisarEvento.setVisible(true);
    }//GEN-LAST:event_miEventoPesquisarActionPerformed

    private void miPessoaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoaPesquisarActionPerformed
        PesquisarPessoa pesquisarPessoa = null;
        try {
            pesquisarPessoa = new PesquisarPessoa();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        pesquisarPessoa.setVisible(true);
    }//GEN-LAST:event_miPessoaPesquisarActionPerformed

    private void miEventoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEventoCriarActionPerformed
        CriarEvento criarEvento = null;
        try {
            criarEvento = new CriarEvento();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        criarEvento.setVisible(true);
    }//GEN-LAST:event_miEventoCriarActionPerformed

    private void miPessoaCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoaCriarActionPerformed
        CriarPessoa criarPessoa = null;
        try {
            criarPessoa = new CriarPessoa();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        criarPessoa.setVisible(true);
    }//GEN-LAST:event_miPessoaCriarActionPerformed

    private void miNovoDocumentoWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoDocumentoWordActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start winword.exe");
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_miNovoDocumentoWordActionPerformed

    private void miNovoDocumentoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoDocumentoExcelActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start excel.exe");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_miNovoDocumentoExcelActionPerformed

    private void miAbrirDocumentoWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirDocumentoWordActionPerformed
        buscar(1);
    }//GEN-LAST:event_miAbrirDocumentoWordActionPerformed

    private void miAbriDocumentoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbriDocumentoExcelActionPerformed
        buscar(2);
    }//GEN-LAST:event_miAbriDocumentoExcelActionPerformed

    private void imgUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUsuarioMouseClicked
        verificaImagem();
    }//GEN-LAST:event_imgUsuarioMouseClicked

    private void miEnviarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEnviarEmailActionPerformed
        try {
            chamaMensagemEvento();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_miEnviarEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel imgUsuario;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    private static javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenu mAnotacoes;
    private javax.swing.JMenu mCriar;
    private javax.swing.JMenu mEmail;
    private javax.swing.JMenu mExcel;
    private javax.swing.JMenu mPesquisar;
    private javax.swing.JMenu mSair;
    private javax.swing.JMenu mSobre;
    private javax.swing.JMenu mWord;
    private javax.swing.JMenuItem miAbriDocumentoExcel;
    private javax.swing.JMenuItem miAbrirDocumentoWord;
    private javax.swing.JMenuItem miEnviarEmail;
    private javax.swing.JMenuItem miEventoCriar;
    private javax.swing.JMenuItem miEventoPesquisar;
    private javax.swing.JMenuItem miNovoDocumentoExcel;
    private javax.swing.JMenuItem miNovoDocumentoWord;
    private javax.swing.JMenuItem miPessoaCriar;
    private javax.swing.JMenuItem miPessoaPesquisar;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables

    public void verificaImagem() {
        String sql = "SELECT * FROM tb_usuario WHERE id_usuario = " + codigoImagem;
        try {
            arrayUsuario = usuarioDAO.PesquisarUsuario(con, sql);
            String img = "";
            int cont = 0;
            while (arrayUsuario.size() > cont) {
                img = arrayUsuario.get(cont).getCaminhoImagem_usuario();
                cont++;
            }
            System.out.println(img);
            if (!(img.equals(""))) {
                BufferedImage imgB = null;
                try {
                    String file = img + ".jpg";
                    String path = new File(".").getCanonicalPath();
                    File nf = new File(path.replace("dist", ""));
                    String arqCaminho = nf + "\\src\\br\\com\\fatecEventos\\imgUsuarios\\" + file;
                    imgB = ImageIO.read(new File(arqCaminho));
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                ImageIcon icon = new ImageIcon(imgB);
                icon.setImage(icon.getImage().getScaledInstance(imgUsuario.getWidth(), imgUsuario.getHeight(), 100));
                imgUsuario.setIcon(icon);
            } else {
                tirarFoto = new TirarFoto(nm, this);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void imgLabel(int nmLabel) throws IOException {
        // diretório que será listado.  
        System.out.println("cheguei");
        String caminho = "src\\br\\com\\fatecEventos\\imgUsuarios";
        File baseFolder = new File(caminho);
        arquivo = (caminho + "\\" + nmLabel + ".jpg");
        // obtem a lista de arquivos  
        BufferedImage img = ImageIO.read(new File(arquivo));
        ImageIcon icon = new ImageIcon(img);
        icon.setImage(icon.getImage().getScaledInstance(imgUsuario.getWidth(), imgUsuario.getHeight(), 100));
        imgUsuario.setIcon(icon);
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.UpdateDados(con, "UPDATE tb_usuario SET caminhoImagem_usuario = '" + nmLabel + "' WHERE id_usuario = " + codigoImagem);
    }

    // Toca o audio do Inicio
    public void tocaAudio() throws UnsupportedAudioFileException {
        try {
            String path = new File(".").getCanonicalPath();
            File nf = new File(path.replace("dist", ""));
            String arqCaminho = nf + "\\src\\br\\com\\fatecEventos\\audio\\BemVindo.wav";

            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(arqCaminho));
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (IOException ioe) {
            System.out.println(ioe);
        } catch (LineUnavailableException lua) {
            System.out.println(lua);
        }
    }

    public void verificaEvento() throws SQLException {
        eventoDAO = new EventoDAO();
        arrayEventos = eventoDAO.PesquisarComboBox(con, "SELECT * FROM tb_evento");
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        String novaData = formatador.format(data);
        int cont = 0;
        while (arrayEventos.size() > cont) {
            if (arrayEventos.get(cont).getDataEvento().equals(novaData)) {
                mEmail.setEnabled(true);
                miEnviarEmail.setEnabled(true);
                try {
                    tocaAudio();
                    nomeEvento = arrayEventos.get(cont).getNomeEvento().toString();
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
//                mEmail.setEnabled(false);
//                miEnviarEmail.setEnabled(false);
            }

            cont++;
        }
    }

    public void buscar(int tipo) {
        FileNameExtensionFilter fileNameExtensionFilter = null;
        if (tipo == 1) {
            // Implementa os tipos de arquivos que apareceram para escolha
            fileNameExtensionFilter = new FileNameExtensionFilter(
                    //descricao , extensões permitidas
                    "Word", "doc", "docx", "txt");
        } else {
            // Implementa os tipos de arquivos que apareceram para escolha
            fileNameExtensionFilter = new FileNameExtensionFilter(
                    //descricao , extensões permitidas
                    "Excel", "xlsx", "xlsm", "csv", "txt");
        }
        //Instânciando o selecionador de arquivos
        JFileChooser fc = new JFileChooser();

        //Adicionando os arquivos que poderam ser selecionados
        fc.setFileFilter(fileNameExtensionFilter);

        //Nome da tela localizadora de arquvios
        fc.setDialogTitle("Escolhendo arquivo");

        //Recebe uma resposta da janela quaso algum evento do localizador de arquivo seja acessado
        int resposta = fc.showOpenDialog(null);

        //Verifica se resposta recebida é igual a ok
        if (resposta == JFileChooser.APPROVE_OPTION) {
            //Se sim abre um buffer do arquivo e joga na tela
            File file = new File(fc.getSelectedFile().getAbsolutePath());
            try {
                Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + file.toString());
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    class CarregaImagem implements Runnable {

        @Override
        public void run() {
            verificaImagem();
        }
    }
}
