/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.fatecEventos.views;

import java.awt.Color;

/**
 *
 * @author lucas
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        this.setLocationRelativeTo(null); // centraliza o FRAME
        Thread t = new Thread(new ProgressBar()); // criando um objeto de Thread e passando como parametro a classe Runnable
        t.start(); // Startando o Thread
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/carregando13.gif"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatecEventos/images/logo-fatec.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 230));
        jPanel1.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 620, 20));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que carrega o splach screen
     */
    class ProgressBar implements Runnable {

        // reescrevendo o método 'run'
        @Override
        public void run() {
            // Aqui estou falando que o background do meu progressBar é branco
            jProgressBar.setBackground(Color.WHITE);
            // Aqui estou pintando ele de Azul
            jProgressBar.setForeground(Color.BLUE);
            // Aqui estou declarando um contador
            jProgressBar.setVisible(false);
            int i = 0;
            // Aqui esta meu Looping
            while (true) {
                // Aqui estou setando valor no progressBar para ele ir ficando colorido
                jProgressBar.setValue(i);
                // Aqui um try para tratar caso haja erro
                try {
                    // Aqui eu mando a Thread dormir uns 30 milesegundos
                    Thread.sleep(30);
                } catch (InterruptedException e) {
                    // Aqui é tratamento do erro e a mensagem
                    System.err.println("Erro ao carregar o sistema.");
                }
                // Aqui ele verifica se o valor do progressBar é igual a 100
                if (i == 100) {
                    // Ai ele fala para a tela ficar dispose();
                    // dispose a tela some e não fecha o programa
                    dispose();
                    // aqui estou falando que a tela não é mais visivel
                    setVisible(false);
                    Login login = new Login();
                    login.setVisible(true);
                }
                // incrementando o valor no contador para não entrar em Looping infinito!
                i++;
            }
        }
    }

}
